### ISSUE TITLE
Comentario sobre tu README

### ISSUE THREAD

**Issue by N1CH** [pdepjm/2021-kata0-prensentacion-marcorodriguezmelgarejo#2]
Puedo confirmarte que funciona.

**Comment by marcorodriguezmelgarejo** [comment]
gracias 👍

**Comment by asanzo** [comment]
Jajajajaj excelente. Los issues sirven para cargar, justamente, "issues" o problemas o preguntas o mejoras a un repositorio de código. El manejo de un proyecto ya caminando suele basarse muchas veces en ordenar los issues y elegir cuáles hacer.
Ahora medio que lo estamos usando para otra cosa, pero si se usa como en la industria, cerrar un issue significa o bien que ya lo resolviste, o bien que no lo vas a resolver.

**Comment by marcorodriguezmelgarejo** [comment]
Entiendo, gracias profe
